#!/bin/bash

# Copyright 2025 Kgateway
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o errexit
set -o nounset
set -o pipefail

FIX=${FIX:-false}
EXIT_CODE=0

# Use git ls-files to respect gitignore
# Filter out deleted files
# Exclude specific directories/files if needed (e.g. autogenerated, though usually we want those consistent too)
files=$(git ls-files)

for f in $files; do
    # check if file exists (git ls-files might list deleted files if not careful, though usually okay)
    if [ ! -f "$f" ]; then
        continue
    fi

    # Skip empty files
    if [ ! -s "$f" ]; then
        continue
    fi
    
    # Skip binary files by checking if they contain null bytes in the first few bytes
    # simple heuristic: grep -I treats the file as binary if it finds a null byte? 
    # Actually, `file` command is safer but slower. 
    # Git knows what is binary.
    # We can use `git grep -I --name-only --untracked -e .` to get all text files?
    # Or just rely on the fact that if it's source code, it should have a newline.
    
    # Let's verify if it's a text file using 'file' command
    mime=$(file --mime "$f")
    if [[ "$mime" != *"text/"* ]] && [[ "$mime" != *"application/json"* ]] && [[ "$mime" != *"application/xml"* ]]; then
        # skips binaries, images, etc.
        continue
    fi

    # Check for trailing newline
    # tail -c1 gets the last byte. If the file has a newline, the last byte is a newline.
    # We read it into a variable. 
    # Warning: command substitution removes trailing newlines!
    # So `x=$(tail -c1 file)` will be empty if the last char is a newline.
    
    # Correct way: use wc or perl/awk
    if [ "$(tail -c1 "$f" | wc -l)" -eq 0 ]; then
        if [ "$FIX" = "true" ]; then
            echo "Fixing newline in $f"
            # Add a newline
            echo "" >> "$f"
        else
            echo "Missing newline: $f"
            EXIT_CODE=1
        fi
    fi
done

exit $EXIT_CODE
